version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bundler-audit
    versions:
    - 0.8.0
  - dependency-name: timecop
    versions:
    - 0.9.3
